server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8


# Mongodb连接信息
mongo:
  host: 127.0.0.1
  port: 27017
  user: verdure
  password: "080928"
  db: admin